name: CnRFlow-0.9.0
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - bioconda::fastqc
 - bioconda::samtools
 - bioconda::picard
 - bioconda::bamtools
 - bioconda::bedtools
 - bioconda::deeptools
 - bioconda::multiqc
 - bioconda::bowtie2
 - bioconda::trimmomatic
 - bioconda::sambamba
 - conda-forge::python
