name: CnRFlow-0.9.0
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - bioconda::fastqc=0.11.9
 - bioconda::samtools=1.10
 - bioconda::picard=2.23.1
 - bioconda::bamtools=2.5.1
 - bioconda::bedtools=2.29.2
 - bioconda::deeptools=3.4.3
 - bioconda::multiqc=1.9
 - bioconda::bowtie2=2.4.4
 - bioconda::trimmomatic=0.39
 - bioconda::sambamba=0.8.1
 - conda-forge::python=3.7.6